apiVersion: v1
kind: Service
metadata:
  name: tawazun-service
  labels:
    name: Hanan
spec:
 selector:
   app: hanan-tawazun-dep
 type: NodePort
 ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001