apiVersion: v1
kind: Service
metadata:
  name: tawazun-svc
  namespace: hanan-tawazun
  labels: 
    name: hanan
spec:
  selector:
    app: tawazun
    service: tawazun-svc
  ports:
    - port: 80 
      targetPort: 8080
  type: LoadBalancer  
  
