apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tawazn-mysql-pv-claim
  labels:
    name: Hanan
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi