apiVersion: v1
kind: PersistentVolume
metadata:
  name: tawazn-mysql-pv
  labels:
    name: Hanan
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql" 